In [2]:
import numpy as pd
li=[1,2,3,4,5]
pd.array(li)

array([1, 2, 3, 4, 5])

In [3]:
ab=[[1,2,3],[4,5,6],[7,8,9]]
pd.array(ab)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
pd.zeros(3)

array([0., 0., 0.])

In [6]:
pd.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
pd.arange(0,10,3)

array([0, 3, 6, 9])

In [8]:
pd.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
pd.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
pd.linspace(0,3,4)

array([0., 1., 2., 3.])

In [12]:
pd.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [13]:
pd.random.rand(10)

array([0.57827159, 0.0933926 , 0.0039729 , 0.89580772, 0.78495503,
       0.99534155, 0.05278483, 0.78808824, 0.22081186, 0.39629317])

In [14]:
pd.random.rand((4))

array([0.77187322, 0.74081   , 0.39892766, 0.72185286])

In [15]:
pd.random.randint(5)

0

In [16]:
pd.random.randn(10)

array([-0.136871  ,  0.61720572,  0.19935999,  1.88653329, -2.07256164,
       -0.1164953 , -2.04134491,  0.97460516, -0.83894859, -0.70062134])

In [17]:
pd.random.randint(1,10)


8

In [18]:
pd.random.randint(1,10,3)

array([5, 9, 6])

In [30]:
import numpy as np
a=np.random.rand(20)
a.reshape(5,4)

array([[0.50437024, 0.96930671, 0.94736635, 0.79448822],
       [0.83428791, 0.82820918, 0.18191224, 0.21870177],
       [0.27540566, 0.51806278, 0.05922896, 0.56614329],
       [0.30351206, 0.19313874, 0.37748743, 0.25322978],
       [0.28024531, 0.17937309, 0.62654702, 0.69064571]])

In [31]:
a.max()

np.float64(0.9693067123911245)

In [32]:
a.min()

np.float64(0.0592289596226665)

In [33]:
a.argmax()


np.int64(1)

In [34]:
a.argmin()

np.int64(10)

In [35]:
a.shape

(20,)

In [36]:
a.dtype

dtype('float64')

In [37]:
a[0]

np.float64(0.5043702372062162)

In [38]:
a[1:5]

array([0.96930671, 0.94736635, 0.79448822, 0.83428791])

In [39]:
a1=a.copy()

In [40]:
a1

array([0.50437024, 0.96930671, 0.94736635, 0.79448822, 0.83428791,
       0.82820918, 0.18191224, 0.21870177, 0.27540566, 0.51806278,
       0.05922896, 0.56614329, 0.30351206, 0.19313874, 0.37748743,
       0.25322978, 0.28024531, 0.17937309, 0.62654702, 0.69064571])

In [45]:
a.reshape(4,5)[2:4,1:5]

array([[0.56614329, 0.30351206, 0.19313874, 0.37748743],
       [0.28024531, 0.17937309, 0.62654702, 0.69064571]])

In [46]:
a>15

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [47]:
boo=a>15

In [49]:
boo

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [50]:
a[boo]

array([], dtype=float64)

In [52]:
a1*2

array([1.00874047, 1.93861342, 1.8947327 , 1.58897643, 1.66857582,
       1.65641837, 0.36382447, 0.43740354, 0.55081133, 1.03612555,
       0.11845792, 1.13228658, 0.60702413, 0.38627749, 0.75497485,
       0.50645956, 0.56049062, 0.35874618, 1.25309403, 1.38129141])

In [53]:
a1+10

array([10.50437024, 10.96930671, 10.94736635, 10.79448822, 10.83428791,
       10.82820918, 10.18191224, 10.21870177, 10.27540566, 10.51806278,
       10.05922896, 10.56614329, 10.30351206, 10.19313874, 10.37748743,
       10.25322978, 10.28024531, 10.17937309, 10.62654702, 10.69064571])